name: Scheduled workflows

on:
  # Allow manual runs through the web UI
  workflow_dispatch:


jobs:
  dispatch_workflows:
    runs-on: ubuntu-slim
    steps:
      - run: gh workflow run spack-ci.yml --repo GEOS-ESM/MAPL --ref main
      - run: gh workflow run spack-ci.yml --repo GEOS-ESM/MAPL --ref develop
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
